# Generated by Django 5.2.5 on 2025-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0002_alter_workoutexercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['workout_id', 'position', 'id']},
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'position'), name='uniq_workout_position'),
        ),
    ]
