# Generated by Django 5.2.5 on 2025-08-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0003_alter_workoutexercise_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutexercise',
            name='uniq_workout_position',
        ),
    ]
