# Generated by Django 5.2.5 on 2025-08-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0004_remove_workoutexercise_uniq_workout_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'position'), name='uniq_workout_position'),
        ),
    ]
