# Generated by Django 5.2.5 on 2025-08-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0005_workoutexercise_uniq_workout_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workoutapi.workoutexercise')),
            ],
            options={
                'ordering': ['workout_exercise_id', 'index', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workout_exercise', 'index'), name='uniq_workout_exercise_set_index')],
            },
        ),
    ]
