# Generated by Django 5.2.5 on 2025-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0008_workouttemplate_workouttemplateexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
