# Generated by Django 5.2.5 on 2025-08-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapi', '0010_alter_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='challenge_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='challenge_window_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
